version: '3'

services:
  database:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main
      PGDATA: /data/postgres
    ports: [5432]
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:

###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
